export enum AuthError {
  INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
  ACCOUNT_PENDING = "ERR_ACCOUNT_PENDING",
  ACCOUNT_BLOCKED = "ERR_ACCOUNT_BLOCKED",
  EMAIL_TAKEN = "ERR_EMAIL_TAKEN",
  TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED",
  TOKEN_INVALID = "ERR_TOKEN_INVALID",
  INTERNAL_ERROR = "ERR_INTERNAL_ERROR",
}

export type UserStatus = "PENDING" | "ACTIVE" | "BLOCKED";

export type VerifyState = 
  | "VERIFYING" 
  | "VERIFY_SUCCESS" 
  | "VERIFY_ALREADY_COMPLETED" 
  | "VERIFY_TOKEN_EXPIRED" 
  | "VERIFY_TOKEN_INVALID" 
  | "VERIFY_SERVER_ERROR";
