import { ATTENDANCE_STATE } from "./attendance-constants";

export const ATTENDANCE_STATE_LIST = [
    ATTENDANCE_STATE.GAME_RUNNING,
    ATTENDANCE_STATE.ATTENDANCE_POPUP_OPEN,
    ATTENDANCE_STATE.ATTENDANCE_DAILY_READY,
    ATTENDANCE_STATE.ATTENDANCE_DAILY_REWARD_POPUP_OPEN,
    ATTENDANCE_STATE.ATTENDANCE_DAILY_DONE,
    ATTENDANCE_STATE.ATTENDANCE_MILESTONE_READY,
    ATTENDANCE_STATE.ATTENDANCE_MILESTONE_DONE,
    ATTENDANCE_STATE.ATTENDANCE_CLOSE_READY,
    ATTENDANCE_STATE.ATTENDANCE_FLOW_DONE,
    ATTENDANCE_STATE.ATTENDANCE_FLOW_FAILED,
] as const;

export type AttendanceStateId = (typeof ATTENDANCE_STATE_LIST)[number];
